import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configure a fonte ppNeueMontreal com todas as variações .otf
const ppNeueMontreal = localFont({
  src: [
    {
      path: "./fonts/ppneue-montreal/ppneuemontreal-thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/ppneue-montreal/ppneuemontreal-book.otf",
      weight: "400", // Assumindo 'book' como regular
      style: "normal",
    },
    {
      path: "./fonts/ppneue-montreal/ppneuemontreal-italic.otf",
      weight: "400", // Assumindo 'italic' como regular itálico
      style: "italic",
    },
    {
      path: "./fonts/ppneue-montreal/ppneuemontreal-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/ppneue-montreal/ppneuemontreal-semibolditalic.otf",
      weight: "600", // Assumindo 'semibold' como 600
      style: "italic",
    },
    {
      path: "./fonts/ppneue-montreal/ppneuemontreal-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pp-neue-montreal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "aiVoice | Web Voice Agents",
  description: "Generated by create next app",
  icons: {
    icon: "/aiVoice.ico", // Caminho do ícone atualizado para .ico
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ppNeueMontreal.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}